runtime: nodejs20
service: default

# Instance class (F1 = free tier, F2 = better performance)
instance_class: F2

# Environment variables (public, non-sensitive only)
env_variables:
  NODE_ENV: "production"
  FRONTEND_URL: "https://notex-app.web.app"
  GCP_PROJECT_ID: "notex-app"
  GCS_BUCKET_NAME: "notex-app-files"

# Automatic scaling
automatic_scaling:
  min_instances: 0
  max_instances: 10
  target_cpu_utilization: 0.65
  target_throughput_utilization: 0.65
  min_idle_instances: 0
  max_idle_instances: 1

# Handlers
handlers:
- url: /.*
  script: auto
  secure: always

# Network settings (for Cloud SQL)
vpc_access_connector:
  name: projects/notex-app/locations/us-central1/connectors/notex-connector

# Beta settings for Cloud SQL
beta_settings:
  cloud_sql_instances: notex-app:us-central1:notex-db